{% set name = "nmrglue" %}
{% set version = environ['VERSION'] %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../

build:
  script_env:
    - VERSION
    - CONDA_BLD_PATH
  string: {{ environ['DEVSTRING'] }}
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
    - python
  host:
    - python
    - numpy
    - pip
    - scipy
  run:
    - python
    - numpy
    - scipy
  test:
    - python             {{ python }}
    - pytest
    - nose

test:
  script_env:
    - VERSION
    - CONDA_BLD_PATH
  imports:
    - nmrglue

about:
  home: "http://www.nmrglue.com"
  license: BSD
  license_family: BSD
  summary: "A module for working with NMR data in Python"

extra:
  recipe-maintainers:
    - fernandezc
