{% set name = "nmrglue" %}
{% set version = environ['VERSION'] %}
{% set devstring = environ['DEVSTRING'] %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../

build:
  script_env:
    - VERSION
    - DEVSTRING
    - CONDA_BLD_PATH
  string: "{{ devstring }}"
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python
  host:
    - python >=3.7
    - pip
  run:
    - numpy
    - scipy
  test:
    - python             {{ python }}

test:
  script_env:
    - VERSION
    - DEVSTRING
    - CONDA_BLD_PATH
  imports:
    - nmrglue

about:
  home: "http://www.nmrglue.com"
  license: BSD
  license_family: BSD
  summary: "A module for working with NMR data in Python"

extra:
  recipe-maintainers:
    - fernandezc
